//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBakeryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailBill
    {
        public int idBill { get; set; }
        public string codePro { get; set; }
        public Nullable<int> quantityPro { get; set; }
        public Nullable<double> totalMoney { get; set; }
        public Nullable<double> priceProBuying { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
    }
}
