//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBakeryShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheBakeryShopEntities : DbContext
    {
        public TheBakeryShopEntities()
            : base("name=TheBakeryShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<detailBill> detailBills { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<style> styles { get; set; }
        public virtual DbSet<tlb_user> tlb_user { get; set; }
    }
}
