//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBakeryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.detailBills = new HashSet<detailBill>();
        }
    
        public string codePro { get; set; }
        public string namePro { get; set; }
        public string descriptionPro { get; set; }
        public Nullable<double> price { get; set; }
        public string size { get; set; }
        public string image { get; set; }
        public string state { get; set; }
        public string codeStyle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailBill> detailBills { get; set; }
        public virtual style style { get; set; }
    }
}
