//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBakeryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBill()
        {
            this.tbDetailBills = new HashSet<tbDetailBill>();
        }
    
        public int idBill { get; set; }
        public Nullable<System.DateTime> billDate { get; set; }
        public int idUser { get; set; }
        public Nullable<double> totalBuy { get; set; }
    
        public virtual tbUser tbUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetailBill> tbDetailBills { get; set; }
    }
}
