//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBakeryShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbDetailBill
    {
        [DisplayName("Mã đơn hàng")]
        [Required(ErrorMessage = "not empty")]
        public int idBill { get; set; }

        [DisplayName("Mã SP")]
        [Required(ErrorMessage = "not empty")]
        public string codePro { get; set; }

        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "not empty")]
        public Nullable<int> quantityPro { get; set; }

        [DisplayName("Thành tiền")]
        [Required(ErrorMessage = "not empty")]
        public Nullable<double> totalMoney { get; set; }

        [DisplayName("Giá")]
        [Required(ErrorMessage = "not empty")]
        public Nullable<double> priceProBuying { get; set; }
    
        public virtual tbBill tbBill { get; set; }
        public virtual tbProduct tbProduct { get; set; }
    }
}
