//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBakeryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProduct()
        {
            this.tbDetailBills = new HashSet<tbDetailBill>();
        }
    
        public string codePro { get; set; }
        public string namePro { get; set; }
        public string descriptionPro { get; set; }
        public Nullable<double> pricePro { get; set; }
        public string sizePro { get; set; }
        public string imagePro { get; set; }
        public string statePro { get; set; }
        public string codeStyle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetailBill> tbDetailBills { get; set; }
        public virtual tbStyle tbStyle { get; set; }
    }
}
