//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBakeryShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProduct()
        {
            this.tbDetailBills = new HashSet<tbDetailBill>();
        }

        [DisplayName("Mã SP")]
        [Required(ErrorMessage = "not empty")]
        public string codePro { get; set; }

        [DisplayName("Tên SP")]
        [Required(ErrorMessage = "not empty")]
        public string namePro { get; set; }

        [DisplayName("Chi tiết")]
        [Required(ErrorMessage = "not empty")]
        public string descriptionPro { get; set; }

        [DisplayName("Giá")]
        [Required(ErrorMessage = "not empty")]
        public Nullable<double> pricePro { get; set; }

        [DisplayName("Kích thước")]
        [Required(ErrorMessage = "not empty")]
        public string sizePro { get; set; }

        [DisplayName("Hình ảnh")]
        [Required(ErrorMessage = "not empty")]
        public string imagePro { get; set; }

        [DisplayName("Tình trạng")]
        [Required(ErrorMessage = "not empty")]
        public string statePro { get; set; }

        [DisplayName("Phân loại")]
        [Required(ErrorMessage = "not empty")]
        public string codeStyle { get; set; }

        [NotMapped]
        public string NameStyle { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetailBill> tbDetailBills { get; set; }
        public virtual tbStyle tbStyle { get; set; }
    }
}
