//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBakeryShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUser()
        {
            this.tbBills = new HashSet<tbBill>();
        }

        [DisplayName("ID User")]
        [Required(ErrorMessage = "not empty")]
        public int idUser { get; set; }

        [DisplayName("Tên ng??i dùng")]
        [Required(ErrorMessage = "Không ???c ?? tr?ng tên ??ng nh?p")]
        public string userName { get; set; }

        [DisplayName("M?t kh?u")]
        [Required(ErrorMessage = "Không ???c ?? tr?ng m?t kh?u")]
        public string userPass { get; set; }

        [NotMapped]
        [DisplayName("Nh?p l?i m?t kh?u")]
        [Required(ErrorMessage = "Không ???c ?? tr?ng")]
        [Compare("userPass")]
        public string RePass { get; set; }

        public string codeCus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBill> tbBills { get; set; }
    }
}
